apiVersion: apps/v1
kind: Deployment
metadata:
  name: depi-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depi-app
  template:
    metadata:
      labels:
        app: depi-app
    spec:
      containers:
      - name: depi-app
        image: mohamed907/depi-project  # Correct image name
        ports:
        - containerPort: 5000
